### ISSUE TITLE
It looks wonderful, but how does it work?

### ISSUE THREAD

**Issue by priyadarshan** [Fuco1/justify-kp#1]
I have just found out about justify-kp, it looks like what I have been looking for so long, but how does it work?

I have cloned the repo, and require it via `use-package`:

```
(use-package justify-kp-new
  :load-path "site-lisp/justify-kp")
```

I can see now there is a new command, `pj-justify`, working on one line, but it does not seem to do anything.

I looked into `justify-kp-old.el` too, I can see there is `pj-justify-paragraph` and `pj-justify-paragraph-2`, but they do not seem to do anything too.

Is there anything to set first?

Thanks!

**Comment by Fuco1** [comment]
There seems to be a bug in dash dependency.  I pushed a fix.

All you need to do is to load `justify-kp.el` and call `pj-justify`, it will justify the line (paragraph).

**Comment by priyadarshan** [comment]
Wow, thank you. It does look much better that default `set-justification-full`. A real gem, thank you!
