### ISSUE TITLE
Possibly add to README usage detail?

### ISSUE THREAD

**Issue by lispstudent** [Fuco1/justify-kp#11]
Hello,
Would it be possible to add to README that `pj-justify` needs to work on an unfilled paragraph, cursor at beginning of line?

In my case, I added this to my init.el:

```
(defun apply-pj-justify ()
  "pj-justify needs to work on an unfilled paragraph, cursor at
bol."
  (interactive)
  (unfill-paragraph)
  (beginning-of-line)
  (pj-justify))
```

Thank you again for this, it is hugely useful.

**Comment by Fuco1** [comment]
Hi @lispstudent 

I've added some more interactive functions for more convenient use.  They are documented in the README. Thanks!

**Comment by lispstudent** [comment]
Thank you so much to clarify and adding those useful features.  I am using `justify-kp` daily, it makes such a big difference for my writing.  Thank you!

**Comment by Fuco1** [comment]
I'm really surprised someone is actually using this package, I wrote it almost 10 years ago actually as a dare from someone on the  Emacs IRC channel :D I'm glad it's useful :blush:

**Comment by lispstudent** [comment]
This package is so good. I wish more people would know about it. It is leaps and bounds better than many justification tools I tried, including for example [par]( http://www.nicemice.net/par/ ). Thank you again.
